--Comprobacion de tablas
--Tabla 1
SELECT * FROM DIM_EXPORTER

--Tabla 2
SELECT * FROM DIM_IMPORTER

--Tabla 3
SELECT * FROM DIM_PRODUCT

--Tabla 4
SELECT * FROM DIM_UNIT

--Tabla 5
SELECT * FROM DIM_YEAR

--Tabla 6, VERIFICANDO VALORES NULOS
SELECT * FROM MAIN_TABLE 
WHERE UNIT_VALUE IS NULL
ORDER BY TRADE_VALUE ASC;

--ELIMINANDO VALORES NULOS
DELETE FROM MAIN_TABLE 
WHERE UNIT_VALUE IS NULL
COMMIT;

--TRABAJANDO CON 3 DECIMALES
UPDATE MAIN_TABLE
SET 
    TRADE_VALUE = ROUND(TRADE_VALUE, 3),
    QUANTITY = ROUND(QUANTITY, 3),
    UNIT_VALUE = ROUND(UNIT_VALUE, 3);
COMMIT;
--PROBANDO CON 55 FILAS
SELECT * FROM(SELECT * FROM  MAIN_TABLE
              ORDER BY TRADE_VALUE ASC)
WHERE ROWNUM <=55;
